FROM golang:1.8

RUN mkdir -p /etc/krakend

RUN go get -v github.com/devopsfaith/krakend/examples/negroni
RUN go install github.com/devopsfaith/krakend/examples/negroni

CMD [ "negroni", "-d", "-p", "8080", "-c", "/etc/krakend/krakend.json" ]