global:
  scrape_interval: 15s
  external_labels:
    monitor: kotel_monitor

scrape_configs:
  - job_name: kotel_example
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets:
        - '${KRAKEND_LOCAL_IP}:59091'
        - '${KRAKEND_LOCAL_IP}:59092'
        - '${KRAKEND_LOCAL_IP}:59093'
        labels:
          app: kotel_example
